name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
        AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
        
